apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  serviceName: mongodb
  minReadySeconds: 10
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:4.4.3
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: "/etc/mongo-credentials/MONGO_ROOT_USERNAME"
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: "/etc/mongo-credentials/MONGO_ROOT_PASSWORD"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-pv
          mountPath: /data/db
        - name: mongodb-configmap
          mountPath: /config
        - name: mongodb-secret
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongodb-pv
        persistentVolumeClaim:
          claimName: mongodb-pvc
      - name: mongodb-configmap
        configMap:
          name: mongodb-configmap
          items:
          - key: mongo.conf
            path: mongo.conf
      - name: mongodb-secret
        secret:
          secretName: mongodb-secret

