trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'manifests'
    publishLocation: 'Container'
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'manifests'
    itemPattern: '**/*.yaml'
    targetPath: '$(System.ArtifactsDirectory)'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-kubernetes-service-connection'
    command: 'apply'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    workingDirectory: '$(System.ArtifactsDirectory)/kubernetes/backend'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-kubernetes-service-connection'
    command: 'apply'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    workingDirectory: '$(System.ArtifactsDirectory)/kubernetes/frontend'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-kubernetes-service-connection'
    command: 'apply'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    workingDirectory: '$(System.ArtifactsDirectory)/kubernetes/mongodb'