trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'manifests'
    publishLocation: 'Container'
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'manifests'
    itemPattern: '**/*.yaml'
    targetPath: '$(System.ArtifactsDirectory)'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'azure-kubernetes-service-connection'
    manifests: '$(System.ArtifactsDirectory)/kubernetes/backend'
    containers: 'yusuffranklin/karsajobs:latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'azure-kubernetes-service-connection'
    manifests: '$(System.ArtifactsDirectory)/kubernetes/frontend'
    containers: 'yusuffranklin/karsajobs-ui:latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'azure-kubernetes-service-connection'
    manifests: '$(System.ArtifactsDirectory)/kubernetes/mongodb'
    containers: 'mongo:4.4.3'