version: "2.16"

services:
  item-app:
    image: yusuffranklin/item-app:v1
    ports:
      - 80:8080
    depends_on:
      item-db:
        condition: service_started
    restart: always
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always
volumes:
  app-db:
