apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: karsajobs-backend
      labels:
        app: backend
    spec:
      containers:
      - name: karsajobs-backend
        image: yusuffranklin/karsajobs:latest
        ports:
          - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_ROOT_PASSWORD
