apiVersion: v1
kind: Service
metadata:
  name: karsajobs-frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  selector:
    app: frontend
  type: NodePort
